// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/galera-healthcheck/monit_wrapper"
)

type FakeMonitWrapper struct {
	SummaryStub        func() string
	summaryMutex       sync.RWMutex
	summaryArgsForCall []struct{}
	summaryReturns struct {
		result1 string
	}
}

func (fake *FakeMonitWrapper) Summary() string {
	fake.summaryMutex.Lock()
	fake.summaryArgsForCall = append(fake.summaryArgsForCall, struct{}{})
	fake.summaryMutex.Unlock()
	if fake.SummaryStub != nil {
		return fake.SummaryStub()
	} else {
		return fake.summaryReturns.result1
	}
}

func (fake *FakeMonitWrapper) SummaryCallCount() int {
	fake.summaryMutex.RLock()
	defer fake.summaryMutex.RUnlock()
	return len(fake.summaryArgsForCall)
}

func (fake *FakeMonitWrapper) SummaryReturns(result1 string) {
	fake.SummaryStub = nil
	fake.summaryReturns = struct {
		result1 string
	}{result1}
}

var _ monit_wrapper.MonitWrapper = new(FakeMonitWrapper)
